### ISSUE TITLE
config: Namespace system for bot.plugins and bot.middleware

### ISSUE THREAD

**Issue by alexeek** [alexeek/canoe#3]
The completion of this will allow the `plugins` map to include something like

```json
{
    "canoe": {
        "core": [
            cmd,
            cmd,
            ...
        ]
    }
}
```

and the config to hold

```yaml
bot:
    plugins:
        - canoe # for all plugins in the namespace
        - canoe.core # for the individual plugin
```
